### ISSUE TITLE
Software Page Formatting

### ISSUE THREAD

**Issue by Emeraldz54** [ArdreyKellMakerClub/ArdreyKellMakerClub.github.io#14]
Something about just doesn't want to work properly. Headers, maybe?

**Comment by daedalus1235** [comment]
if it's about "Missing Subtitle" you need to add a subtitle: "" to the front matter

**Comment by daedalus1235** [comment]
also you link to homepage goes to 404

**Comment by daedalus1235** [comment]
didn't you fix it. you need to remember to close issues
