### ISSUE TITLE
Nav Bar formatting weird.

### ISSUE THREAD

**Issue by daedalus1235** [ArdreyKellMakerClub/ArdreyKellMakerClub.github.io#16]
@Emeraldz54  pls fix

**Comment by Emeraldz54** [comment]
I Think it looks fine. Tell me how you want it formatted or something other than it looks weird.
@daedalus1235

**Comment by daedalus1235** [comment]
i'd like the weird square thing next to dropdowns to be fixed @Emeraldz54

**Comment by daedalus1235** [comment]
the weird square things are a thing again @Emeraldz54

**Comment by Emeraldz54** [comment]
just don't touch the website. Then the source of the problem goes away @daedalus1235
