### ISSUE TITLE
Systems.md

### ISSUE THREAD

**Issue by Emeraldz54** [ArdreyKellMakerClub/ArdreyKellMakerClub.github.io#20]
Someone get Vatsal to get me something about what he plans on doing for systems and explain it to someone.

I still have no idea how systems works.

**Comment by daedalus1235** [comment]
dude just mention @Tornado145

**Comment by XessWaffle** [comment]
Systems is essentially the integration of Hardware and software. Anyone in systems will build and program simultaneously to achieve a goal. My plan was initially to have them build circuits with the arduino or raspberry pi. The ultimate goal is for them to be able to manipulate machinery in the physical world with code designed to do what they want it to do.

Edit:
I updated systems.md and am closing this issue.
