### ISSUE TITLE
Is there any way to get rid of the blue VIEW ON GITHUB thingy?

### ISSUE THREAD

**Issue by Emeraldz54** [ArdreyKellMakerClub/ArdreyKellMakerClub.github.io#24]
It just looks really out of place. It would look nicer, but is not necessary.

**Comment by daedalus1235** [comment]
yes, it's really easy--just need to delete one line in one file--but i like it @Emeraldz54

**Comment by daedalus1235** [comment]
got rid of the forkme flag @Emeraldz54 happy?
