### ISSUE TITLE
Bullet points and the words after them are invisible

### ISSUE THREAD

**Issue by XessWaffle** [ArdreyKellMakerClub/ArdreyKellMakerClub.github.io#26]
After updating Systems.md, the Divisions/Systems page did update, however, the bullet points that listed the rules were, instead of being words, black strips that did not reveal any text.

**Comment by Emeraldz54** [comment]
@Tornado145 
Sooooooooo lists are weird on Github. I'll take a look at it.
Also the site doesn't get published immediately, so you may need to wait a minute before seeing any changes.

Also next time mention me or Charles so that we are notified of any issues quicker.

**Comment by XessWaffle** [comment]
Alright got it.

**Comment by daedalus1235** [comment]
just do @ArdreyKellMakerClub/admins by typing @/ad
