### ISSUE TITLE
Calendar Broken

### ISSUE THREAD

**Issue by daedalus1235** [ArdreyKellMakerClub/ArdreyKellMakerClub.github.io#29]
@ArdreyKellMakerClub/admins either the calendar is broken or @inSaneSyntax deleted every entry. Either way i'm blaming daniel

**Comment by daedalus1235** [comment]
@inSaneSyntax deleted every entry. don't delete past entries. only delete incorrect entries.

**Comment by danielyhwang** [comment]
STOP BLAMING ME CHARLES I DIDN'T DO SHIT THIS IS YOUR FAULT
